name: docker_image
on:
 
  pull_request:
    branches: ['main']
jobs:
  build_push_i:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_username }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: username/reponame:trail
  pull_doc_img:
    runs-on: ubuntu-latest  
    needs: build_push_i
    if: ${{ needs.build_push_i.result == 'success' }}
    steps:
      - name: Pull Docker image
        run: docker pull username/repoName:VersionName
      - name: R_containeer
        run: |
          OUTPUT=$(docker run username/repoName:VersionName)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.30" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
          echo "successfull executed!"
  fail-job:
      runs-on: ubuntu-latest  
      needs: build_push_i
      if: ${{ failure() }}
      steps:
      - name: fail job
        run: |
          echo "Fail the job"
          exit 1
