name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    needs: Train

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image from registry
        run: docker pull rajaj01100/project:v1

      - name: Run Docker container and test model
        run: |
          docker run rajaj01100/project:v1 python test.py
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
