name: Train
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t yourdockerhubusername/cicd_assignment:${{ github.sha }} .
        
      - name: Push Docker image to registry
        run: |
          echo "${{ secret["@Machine1'] }}" | docker login -u "${{ secrets.rajaj0110 }}" --password-stdin
          docker push yourdockerhubusername/cicd_assignment:${{ github.sha }}
        if: success()
